name: Create Issue Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/CHANGELOG.md'
      - '**/package.json'
  pull_request:
  workflow_dispatch:

jobs:
  publish_firefox_extension:
    name: Publish Firefox extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Issue for Firefox Manual Step 
        id: create-firefox-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/FIREFOX_ISSUE_TEMPLATE.md
          update_existing: true
        run: |
          echo "Created issue number ${{ steps.create-firefox-issue.outputs.number }}"
          echo "Created ${{ steps.create-firefox-issue.outputs.url }}"
