      - name: Publish Statuses
        run: |
          echo Created issue number ${{ steps.create-firefox-issue.outputs.number }}
          echo Created ${{ steps.create-firefox-issue.outputs.url }}
